### PR TITLE
Fix #119

### LINKED ISSUE #119: No Social Network logo
image

### PR DESCRIPTION
**Pull request by koonwill**

### CODE REVIEW

**Comment by koonwill** [comment]
conflict solved please review

**Review by Tezigudo — DISMISSED** [review]
👍

**Review by ThanadolU — DISMISSED** [review]
Good job

**Review by thanidacwn — DISMISSED** [review]
+1

**Review by Tezigudo — APPROVED** [review]
Good Doog 👍

**Review by ThanadolU — APPROVED** [review]
✅

**Comment by koonwill** [comment]
ready to merge

**Comment by koonwill** [comment]
merge success

**Pull request merged**
