### PR TITLE
fix message to center of page 

### PR DESCRIPTION
**Pull request by thanidacwn**

### CODE REVIEW

**Comment by Tezigudo** [comment]
👎

**Comment by Tezigudo** [comment]
image
here

**Review by Tezigudo — CHANGES_REQUESTED** [review]
Its doesnt went right fix it

**Comment by thanidacwn** [comment]
fixed
Screen Shot 2565-11-26 at 10 32 16

Screen Shot 2565-11-26 at 10 33 09

**Review by Tezigudo — DISMISSED** [review]
👍

**Comment by Tezigudo** [comment]
> **fixed**
> 
> Screen Shot 2565-11-26 at 10 32 16
> 
> Screen Shot 2565-11-26 at 10 35 11

Last condition seem you use the word `No History avaliable` its better ( i suggested)

**Comment by thanidacwn** [comment]
Add condition `No History avaliable`

Screen Shot 2565-11-26 at 11 42 03

**Review by koonwill — APPROVED** [review]
Good work.

**Pull request merged**
